//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPact.Mowbly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Properties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudPact.Mowbly.Resources.Properties", typeof(Properties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enterprise.
        /// </summary>
        internal static string APP_TYPE {
            get {
                return ResourceManager.GetString("APP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mowbly/app.
        /// </summary>
        internal static string DIR_APP {
            get {
                return ResourceManager.GetString("DIR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mowbly/bak.
        /// </summary>
        internal static string DIR_BAK {
            get {
                return ResourceManager.GetString("DIR_BAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mowbly/cache.
        /// </summary>
        internal static string DIR_CACHE {
            get {
                return ResourceManager.GetString("DIR_CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mowbly/documents.
        /// </summary>
        internal static string DIR_DOCS {
            get {
                return ResourceManager.GetString("DIR_DOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mowbly/logs.
        /// </summary>
        internal static string DIR_LOGS {
            get {
                return ResourceManager.GetString("DIR_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /shared/transfers.
        /// </summary>
        internal static string DIR_SHARED_TRANSFER {
            get {
                return ResourceManager.GetString("DIR_SHARED_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mowbly/tmp.
        /// </summary>
        internal static string DIR_TMP {
            get {
                return ResourceManager.GetString("DIR_TMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera=CloudPact.MowblyFramework.Core.Features.Camera
        ///contacts=CloudPact.MowblyFramework.Core.Features.Contacts
        ///database=CloudPact.MowblyFramework.Core.Features.Database
        ///device=CloudPact.MowblyFramework.Core.Features.Device
        ///file=CloudPact.MowblyFramework.Core.Features.File
        ///framework=CloudPact.MowblyFramework.Core.Features.Framework
        ///geolocation=CloudPact.MowblyFramework.Core.Features.GeoLocation
        ///http=CloudPact.MowblyFramework.Core.Features.Http
        ///logger=CloudPact.MowblyFramework.Core.Features.Log
        ///mess [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FEATURES {
            get {
                return ResourceManager.GetString("FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mowbly.
        /// </summary>
        internal static string FRAMEWORK {
            get {
                return ResourceManager.GetString("FRAMEWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.0.
        /// </summary>
        internal static string FRAMEWORK_VERSION {
            get {
                return ResourceManager.GetString("FRAMEWORK_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30000.
        /// </summary>
        internal static string HTTP_REQUEST_TIMEOUT {
            get {
                return ResourceManager.GetString("HTTP_REQUEST_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40000.
        /// </summary>
        internal static string LOG_DEFAULT_THRESHOLD {
            get {
                return ResourceManager.GetString("LOG_DEFAULT_THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs.
        /// </summary>
        internal static string LOGS_DB {
            get {
                return ResourceManager.GetString("LOGS_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string LOGS_DB_VERSION {
            get {
                return ResourceManager.GetString("LOGS_DB_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __mowbly.log.
        /// </summary>
        internal static string LOGS_FILE {
            get {
                return ResourceManager.GetString("LOGS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windows.
        /// </summary>
        internal static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com.cloudpact.mowbly.Home.
        /// </summary>
        internal static string TITLE_HOME_PAGE {
            get {
                return ResourceManager.GetString("TITLE_HOME_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mowbly Magic/index.html.
        /// </summary>
        internal static string URL_HOME_PAGE {
            get {
                return ResourceManager.GetString("URL_HOME_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pnf.html.
        /// </summary>
        internal static string URL_PAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("URL_PAGE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
