//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPact.Mowbly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudPact.MowblyFramework.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled activity.
        /// </summary>
        internal static string ACTIVITY_CANCELLED {
            get {
                return ResourceManager.GetString("ACTIVITY_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for external power / WiFi.
        /// </summary>
        internal static string BACKGROUND_TRANSFER_WAITING {
            get {
                return ResourceManager.GetString("BACKGROUND_TRANSFER_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error capturing picture. Reason - .
        /// </summary>
        internal static string CAMERA_CAPTURE_ERROR {
            get {
                return ResourceManager.GetString("CAMERA_CAPTURE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error formatting picture. Reason -.
        /// </summary>
        internal static string CAMERA_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("CAMERA_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing camera.
        /// </summary>
        internal static string CAMERA_INITIALIZATION_ERROR {
            get {
                return ResourceManager.GetString("CAMERA_INITIALIZATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing picture. Reason - .
        /// </summary>
        internal static string CAMERA_PROCESS_PICTURE_ERROR {
            get {
                return ResourceManager.GetString("CAMERA_PROCESS_PICTURE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing picture to file. Reason - .
        /// </summary>
        internal static string CAMERA_WRITE_PICTURE_ERROR {
            get {
                return ResourceManager.GetString("CAMERA_WRITE_PICTURE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error picking contact. Reason - .
        /// </summary>
        internal static string CONTACT_CHOOSE_FAILED {
            get {
                return ResourceManager.GetString("CONTACT_CHOOSE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting contact. Reason -.
        /// </summary>
        internal static string CONTACT_DELETE_ERROR {
            get {
                return ResourceManager.GetString("CONTACT_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact not found.
        /// </summary>
        internal static string CONTACT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CONTACT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving contact. Reason - .
        /// </summary>
        internal static string CONTACT_SAVE_FAILED {
            get {
                return ResourceManager.GetString("CONTACT_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search parameter missing..
        /// </summary>
        internal static string CONTACT_SEARCH_PARAM_MISSING {
            get {
                return ResourceManager.GetString("CONTACT_SEARCH_PARAM_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error viewing contact. Reason - .
        /// </summary>
        internal static string CONTACT_VIEW_FAILED {
            get {
                return ResourceManager.GetString("CONTACT_VIEW_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading contacts....
        /// </summary>
        internal static string CONTACTS_LOADING {
            get {
                return ResourceManager.GetString("CONTACTS_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection is currently open.
        /// </summary>
        internal static string DATABASE_NO_CONNECTION_OPEN_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_NO_CONNECTION_OPEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database transaction is not active.
        /// </summary>
        internal static string DATABASE_NO_TRANSACTION_ACTIVE_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_NO_TRANSACTION_ACTIVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening database. Reason -.
        /// </summary>
        internal static string DATABASE_OPEN_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_OPEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in database operation. Reason - .
        /// </summary>
        internal static string DATABASE_OPERATION_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_OPERATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing query. Reason - .
        /// </summary>
        internal static string DATABASE_QUERY_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_QUERY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in transaction. Reason -.
        /// </summary>
        internal static string DATABASE_TRANSACTION_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_TRANSACTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External storage not available or not ready.
        /// </summary>
        internal static string EXTERNAL_STORAGE_ERROR {
            get {
                return ResourceManager.GetString("EXTERNAL_STORAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not reachable. Check connectivity or try again later..
        /// </summary>
        internal static string HOST_NOT_REACHABLE {
            get {
                return ResourceManager.GetString("HOST_NOT_REACHABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connectivity. Try again later..
        /// </summary>
        internal static string NO_CONNECTIVITY {
            get {
                return ResourceManager.GetString("NO_CONNECTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
